from django.db import models

class PopulationData(models.Model):
    state = models.TextField(db_column='State', blank=True, null=True)
    district = models.TextField(db_column='District', primary_key=True)
    persons = models.BigIntegerField(db_column='Persons', blank=True, null=True)
    males = models.BigIntegerField(db_column='Males', blank=True, null=True)
    females = models.BigIntegerField(db_column='Females', blank=True, null=True)
    growth_1991_2001_field = models.FloatField(db_column='Growth..1991...2001.', blank=True, null=True)
    rural = models.FloatField(db_column='Rural', blank=True, null=True)
    urban = models.FloatField(db_column='Urban', blank=True, null=True)
    scheduled_caste_population = models.FloatField(db_column='Scheduled.Caste.population', blank=True, null=True)
    number_of_households = models.FloatField(db_column='Number.of.households', blank=True, null=True)
    sex_ratio_females_per_1000_males_field = models.FloatField(db_column='Sex.ratio..females.per.1000.males.', blank=True, null=True)
    scheduled_tribe_population = models.FloatField(db_column='Scheduled.Tribe.population', blank=True, null=True)
    persons_literate = models.BigIntegerField(db_column='Persons..literate', blank=True, null=True)
    x0_4_years = models.FloatField(db_column='X0...4.years', blank=True, null=True)
    x5_14_years = models.FloatField(db_column='X5...14.years', blank=True, null=True)
    x15_59_years = models.FloatField(db_column='X15...59.years', blank=True, null=True)
    population = models.BigIntegerField(db_column='Population', blank=True, null=True)
    male = models.BigIntegerField(db_column='Male', blank=True, null=True)
    female = models.BigIntegerField(db_column='Female', blank=True, null=True)
    cultivator_workers = models.BigIntegerField(db_column='Cultivator_Workers', blank=True, null=True)
    agricultural_workers = models.BigIntegerField(db_column='Agricultural_Workers', blank=True, null=True)
    household_workers = models.BigIntegerField(db_column='Household_Workers', blank=True, null=True)
    age_group_0_29 = models.BigIntegerField(db_column='Age_Group_0_29', blank=True, null=True)
    age_group_30_49 = models.BigIntegerField(db_column='Age_Group_30_49', blank=True, null=True)
    age_group_50 = models.BigIntegerField(db_column='Age_Group_50', blank=True, null=True)
    growth_2001_2011 = models.FloatField(db_column='Growth_2001_2011', blank=True, null=True)
    literacy_rate = models.FloatField(db_column='Literacy_Rate', blank=True, null=True)
    urban_rate = models.FloatField(db_column='Urban_Rate', blank=True, null=True)
    sc_rate = models.FloatField(db_column='SC_Rate', blank=True, null=True)
    st_rate = models.FloatField(db_column='ST_Rate', blank=True, null=True)
    household_size = models.FloatField(db_column='Household_Size', blank=True, null=True)
    cultivator_rate = models.FloatField(db_column='Cultivator_Rate', blank=True, null=True)
    agricultural_rate = models.FloatField(db_column='Agricultural_Rate', blank=True, null=True)
    age_0_29_rate = models.FloatField(db_column='Age_0_29_Rate', blank=True, null=True)
    age_30_49_rate = models.FloatField(db_column='Age_30_49_Rate', blank=True, null=True)
    age_50_rate = models.FloatField(db_column='Age_50_Rate', blank=True, null=True)
    annual_growth_rate = models.FloatField(db_column='Annual_Growth_Rate', blank=True, null=True)
    population_2012 = models.BigIntegerField(db_column='Population_2012', blank=True, null=True)
    population_2013 = models.BigIntegerField(db_column='Population_2013', blank=True, null=True)
    population_2014 = models.BigIntegerField(db_column='Population_2014', blank=True, null=True)
    population_2015 = models.BigIntegerField(db_column='Population_2015', blank=True, null=True)
    population_2016 = models.BigIntegerField(db_column='Population_2016', blank=True, null=True)
    population_2017 = models.BigIntegerField(db_column='Population_2017', blank=True, null=True)
    population_2018 = models.BigIntegerField(db_column='Population_2018', blank=True, null=True)
    population_2019 = models.BigIntegerField(db_column='Population_2019', blank=True, null=True)
    population_2020 = models.BigIntegerField(db_column='Population_2020', blank=True, null=True)
    population_2021 = models.BigIntegerField(db_column='Population_2021', blank=True, null=True)
    population_2022 = models.BigIntegerField(db_column='Population_2022', blank=True, null=True)
    population_2023 = models.BigIntegerField(db_column='Population_2023', blank=True, null=True)
    population_2024 = models.BigIntegerField(db_column='Population_2024', blank=True, null=True)
    population_2025 = models.BigIntegerField(db_column='Population_2025', blank=True, null=True)
    population_2026 = models.BigIntegerField(db_column='Population_2026', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'population_data'

    def __str__(self):
        return f"{self.district}, {self.state}"
